using System;
using System.Collections.Generic;
using System.Text;

namespace MyCloudProject.Common
{
    // The IExperimentResult interface defines a contract for any experiment result.
    // It includes properties for tracking the experiment's identity, timing, and related information.
    public interface IExperimentResult
    {
        // Unique identifier for the experiment.
        string ExperimentId { get; set; }

        // The UTC start time of the experiment. Nullable to allow for unset start times.
        DateTime? StartTimeUtc { get; set; }

        // The UTC end time of the experiment. Nullable to allow for unset end times.
        DateTime? EndTimeUtc { get; set; }

        // The total duration of the experiment. This is not nullable,
        // so it should be computed or assigned a default value.
        public TimeSpan Duration { get; set; }

        // A brief description of the experiment.
        string Description { get; set; }

        // A string representing the output files generated by the experiment.
        // This could be paths, URLs, or a serialized list depending on implementation.
        string OutputFiles { get; set; }
    }
}
