using Azure;
using Azure.Data.Tables;
using MyCloudProject.Common;
using System;
using System.Collections.Generic;
using System.Text;

namespace MyExperiment
{

    // Represents the result of an experiment, designed to be stored in Azure Table Storage.
    // Implements ITableEntity for Azure compatibility and IExperimentResult for custom behavior.
    public class ExperimentResult : ITableEntity, IExperimentResult
    {
        /// <summary>
        /// Constructor initializes the PartitionKey and RowKey required by Azure Table Storage.
        /// </summary>
        /// <param name="partitionKey">Partition key groups related records in Table Storage.</param>
        /// <param name="rowKey">Row key uniquely identifies a record within a partition.</param>
        public ExperimentResult(string partitionKey, string rowKey)
        {
            // Assign partition and row keys during object creation.
            this.PartitionKey = partitionKey; // Logical group for related entities.
            this.RowKey = rowKey;             // Unique identifier within the partition.
        }

        // Required properties for Azure Table Storage.

        /// <summary>
        /// Partition key for logical grouping of entities in Table Storage.
        /// Entities with the same partition key are stored in the same partition, enabling faster queries.
        /// </summary>
        public string PartitionKey { get; set; }

        /// <summary>
        /// Row key uniquely identifies an entity within a partition.
        /// Combined with PartitionKey, it ensures uniqueness across the table.
        /// </summary>
        public string RowKey { get; set; }

        /// <summary>
        /// Timestamp indicating the last modification time of the entity.
        /// Automatically managed by Azure Table Storage.
        /// </summary>
        public DateTimeOffset? Timestamp { get; set; }

        /// <summary>
        /// ETag used for concurrency control to handle updates safely.
        /// Prevents conflicts when multiple clients attempt to update the same entity simultaneously.
        /// </summary>
        public ETag ETag { get; set; }

        // Custom properties specific to the experiment result.

        /// <summary>
        /// Unique identifier for the experiment, used for tracking purposes.
        /// </summary>
        public string ExperimentId { get; set; }

        /// <summary>
        /// Name or title of the experiment for easy identification.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Short textual description providing additional details about the experiment.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// The UTC start time of the experiment, marking when it began execution.
        /// </summary>
        public DateTime? StartTimeUtc { get; set; }

        /// <summary>
        /// The UTC end time of the experiment, marking when it completed execution.
        /// Null if the experiment is still in progress.
        /// </summary>
        public DateTime? EndTimeUtc { get; set; }

        /// <summary>
        /// Duration of the experiment in seconds, calculated as the difference between EndTimeUtc and StartTimeUtc.
        /// Note: Redundant with 'Duration' property. Consider using one property instead of both.
        /// </summary>
        public long DurationSec { get; set; }

        /// <summary>
        /// Serialized list of output file names generated by the experiment.
        /// Stored as a comma-separated string or JSON format for flexibility.
        /// Example: "[\"output1.txt\",\"output2.csv\"]"
        /// </summary>
        public string OutputFiles { get; set; }

        /// <summary>
        /// The actual duration of the experiment, stored as a TimeSpan object.
        /// Preferred over 'DurationSec' for better time handling and formatting.
        /// </summary>
        public TimeSpan Duration { get; set; }
    }
}
